---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
env:
  es6: true
  node: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- __tests__/
after_success:
- codeclimate < ./tmp/lcov.info
